#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

GUILD_ID=1357557811281793054
CHANNEL_ID=1357557812498272450
# View Channel (1024) + Send Messages (2048) + Embed Links (16384)
# + Read Message History (65536) + Add Reactions (64)
PERMISSIONS=85056

mkdir -p "$HOME/.config/cinemaslime"
chmod 700 "$HOME/.config/cinemaslime"
ENV_FILE="$HOME/.config/cinemaslime/discord-bot.env"
umask 077

# discord_get PATH — authenticated GET against the Discord API. The token goes
# in via curl's stdin config so it never appears in the process list.
discord_get() {
  printf 'header = "Authorization: Bot %s"\n' "$DISCORD_BOT_TOKEN" |
    curl -s -K - -o /dev/null -w '%{http_code}' "https://discord.com/api/v10$1"
}
discord_body() {
  printf 'header = "Authorization: Bot %s"\n' "$DISCORD_BOT_TOKEN" |
    curl -s -K - "https://discord.com/api/v10$1"
}

TOTAL_STAGES=5
TOTAL_MINUTES=10

banner "Cinema Slime Curator — Discord bot setup"

stage "Create the Discord application" 2
say "Links open on this machine's browser if it can; otherwise open them on yours."
open_url "https://discord.com/developers/applications"
step "Click 'New Application' (top right)."
step "Name it: Cinema Slime Curator  ·  accept the terms  ·  Create."
step "On 'General Information', copy the APPLICATION ID."
ask DISCORD_APPLICATION_ID "Paste the Application ID:"
until [[ "$DISCORD_APPLICATION_ID" =~ ^[0-9]{17,20}$ ]]; do
  warn "That doesn't look like an ID (17–20 digits)."
  ask DISCORD_APPLICATION_ID "Paste the Application ID:"
done
write_env DISCORD_APPLICATION_ID "$DISCORD_APPLICATION_ID"

stage "Make it private + leave intents off" 2
open_url "https://discord.com/developers/applications/$DISCORD_APPLICATION_ID/installation"
step "Installation page: set 'Install Link' to None  ·  Save Changes."
note "Discord refuses to make a bot private while an install link is set."
open_url "https://discord.com/developers/applications/$DISCORD_APPLICATION_ID/bot"
step "Bot page: turn OFF 'Public Bot' so nobody else can add it."
step "Leave all three 'Privileged Gateway Intents' OFF."
note "Message Content isn't needed: Discord always shows a bot the messages that @mention it."
step "Save Changes."
pause "Done?"

stage "Bot token" 2
step "Still on the Bot page: click 'Reset Token', confirm (and 2FA if asked)."
step "Click 'Copy'. The token is shown only once."
ask_secret DISCORD_BOT_TOKEN "Paste the bot token (hidden):"
while :; do
  code=$(discord_get /users/@me)
  [[ "$code" == 200 ]] && break
  warn "Discord rejected that token (HTTP $code). Reset it again and paste the new one."
  ask_secret DISCORD_BOT_TOKEN "Paste the bot token (hidden):"
done
me=$(discord_body /users/@me)
DISCORD_BOT_USER_ID=$(printf '%s' "$me" | sed -n 's/.*"id": *"\([0-9]*\)".*/\1/p')
say "Token works: logged in as bot user $DISCORD_BOT_USER_ID."
write_env DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"
write_env DISCORD_BOT_USER_ID "$DISCORD_BOT_USER_ID"
set_secret DISCORD_BOT_TOKEN "$DISCORD_BOT_TOKEN"

stage "Add the bot to the Cinema Slime server" 2
open_url "https://discord.com/oauth2/authorize?client_id=$DISCORD_APPLICATION_ID&scope=bot&permissions=$PERMISSIONS&guild_id=$GUILD_ID&disable_guild_select=true"
step "Server should be pre-selected: Cinema Slime Podcast  ·  Continue."
step "Leave every permission checked  ·  Authorize."
pause "Authorized?"
until [[ "$(discord_body /users/@me/guilds)" == *"\"$GUILD_ID\""* ]]; do
  warn "The bot isn't in the server yet. Re-open the link above and authorize."
  pause "Try again?"
done
say "Bot is in the server."

stage "Let it into #admin-convos" 2
open_url "https://discord.com/channels/$GUILD_ID/$CHANNEL_ID"
step "Hover #admin-convos  ·  click the gear (Edit Channel)  ·  Permissions."
step "Under the private-channel section, click 'Add members or roles'."
step "Search 'Cinema Slime Curator', tick it  ·  Done."
pause "Added?"
while :; do
  view=$(discord_get "/channels/$CHANNEL_ID")
  hist=$(discord_get "/channels/$CHANNEL_ID/messages?limit=1")
  [[ "$view" == 200 && "$hist" == 200 ]] && break
  warn "Bot still can't read #admin-convos (view $view, history $hist). Re-check the channel permissions."
  pause "Try again?"
done
say "Bot can see #admin-convos and read its history."

finish
say "Values live in $ENV_FILE (mode 600). Tell Claude it's done."
